---
- name: start NetworkManager dispatcher
  systemd:
    name: NetworkManager-dispatcher.service
    state: started
  when: ansible_virtualization_role == "host" or ansible_virtualization_role == "NA"

- name: start NetworkManager
  systemd:
    name: NetworkManager.service
    state: started
  when: ansible_virtualization_role == "host" or ansible_virtualization_role == "NA"
