---
- name: reload systemd config
  ansible.builtin.command: systemctl daemon-reload
  when: ansible_virtualization_role == "host" or ansible_virtualization_role == "NA"

- name: start base services
  ansible.builtin.systemd: name={{ item }}.service state=started
  with_items: "{{ enabled_services }}"
  when: ansible_virtualization_role == "host" or ansible_virtualization_role == "NA"

- name: start additional services
  ansible.builtin.systemd: name={{ item }}.service state=started
  with_items: "{{ additional_enabled_services }}"
  when: ansible_virtualization_role == "host" or ansible_virtualization_role == "NA"
