---
- name: restart tlp
  systemd: name=tlp.service state=restarted
  when: ansible_virtualization_role == "host" or ansible_virtualization_role == "NA"

- name: restart lowbatt
  systemd: name=lowbatt.timer state=restarted
  when: ansible_virtualization_role == "host" or ansible_virtualization_role == "NA"

- name: start lowbatt
  systemd: name=lowbatt.timer state=started
  when: ansible_virtualization_role == "host" or ansible_virtualization_role == "NA"
