---
- name: restart tlp
  systemd: name=tlp.service state=restarted
  when: running_in_chroot == False

- name: restart lowbatt
  systemd: name=lowbatt.timer state=restarted
  when: running_in_chroot == False

- name: start lowbatt
  systemd: name=lowbatt.timer state=started
  when: running_in_chroot == False
