---
- name: start udiskie
  become: yes
  become_user: "{{ user.name }}"
  systemd:
    name: udiskie.service
    state: started
    scope: user
  when: ansible_virtualization_role == "host" or ansible_virtualization_role == "NA"
