---
- name: Create Chezmoi config dir
  become_user: "{{ user.name }}"
  become: yes
  file: path="/home/{{ user.name }}/.config/chezmoi" state=directory mode=0755 recurse=yes

- name: Create chezmoi config
  template:
    src: chezmoi.toml
    dest: "/home/{{ user.name }}/.config/chezmoi/chezmoi.toml"

- name: Clone dotfiles to user home
  become_user: "{{ user.name }}"
  become: yes
  ansible.builtin.command: "chezmoi init --cache /home/{{ user.name }}/.cache/chezmoi --source /home/{{ user.name }}/.local/share/chezmoi -D /home/{{ user.name }} --no-tty --force --apply --verbose {{ user.dotfiles }}"

- name: Creates directory for runable scripts
  become_user: "{{ user.name }}"
  become: yes
  file:
    path: "/home/{{ user.name }}/.local/bin"
    state: directory
    mode: 0775
    recurse: yes

- name: Copy zshrc to root
  synchronize:
    dest: "/root/"
    src: "/home/{{ user.name }}/.zshrc"
    archive: no
  notify: zplug install as root

- name: Copy powerlevel to root
  synchronize:
    dest: "/root/"
    src: "/home/{{ user.name }}/.p10k.zsh"
    archive: no
