---
- import_role:
    name: graphical/video-drivers

- import_role:
    name: graphical/user-packages

- import_role:
    name: graphical/clipboard

- import_role:
    name: graphical/logitech
  tags: [logitech]

- import_role:
    name: graphical/media

- import_role:
    name: graphical/udisks

- import_role:
    name: graphical/pipewire

- import_role:
    name: graphical/bluetooth
  when: bluetooth is defined

- import_role:
    name: graphical/display-temperature

- import_role:
    name: graphical/virtualbox
  tags: [virtualbox]

- import_role:
    name: graphical/networkmanager

- import_role:
    name: graphical/nmtrust
  when: ansible_distribution == 'Archlinux'
