---
- debug:
    msg: "Running system tasks"

- import_role:
    name: system/bootloader
  when: bootloader is defined

- import_role:
    name: system/base

- import_role:
    name: system/ntp

- import_role:
    name: system/docker

- import_role:
    name: system/filesystems
