---
- debug:
    msg: "Running system tasks"

- import_role:
    name: bootloader
  when: bootloader is defined

- import_role:
    name: base

- import_role:
    name: ntp

- import_role:
    name: docker

- import_role:
    name: filesystems
