---
- name: Clone dotfiles to user home
  become_user: "{{ user.name }}"
  become: yes
  command: "chezmoi init --apply --verbose -W /home/{{ user.name }} {{ user.dotfiles }}"

- name: Creates directory for runable scripts
  become_user: "{{ user.name }}"
  become: yes
  file:
    path: "/home/{{ user.name }}/.local/bin"
    state: directory
    mode: 0775
    recurse: yes

- name: Copy zshrc to root
  synchronize:
    dest: "/root/"
    src: "/home/{{ user.name }}/.zshrc"
    archive: no
  notify: zplug install as root

- name: Copy powerlevel to root
  synchronize:
    dest: "/root/"
    src: "/home/{{ user.name }}/.p10k.zsh"
    archive: no
