---
- name: dotfiles | yadm dotfiles manager
  ansible.builtin.package:
    name: yadm

- name: dotfiles | check dotfiles already cloned.
  become: true
  ansible.builtin.stat:
    path: /home/{{ user.name }}/.local/share/yadm/repo.git
  register: dotfiles

- name: dotfiles | clone dotfiles project
  ansible.builtin.command: "yadm clone --bootstrap {{ user.dotfiles }}"
  become: true
  become_user: "{{ user.name }}"
  when: not dotfiles.stat.exists

- name: Copy zshrc to root
  synchronize:
    dest: "/root/"
    src: "/home/{{ user.name }}/.zshrc"
    archive: no
  notify: zplug install as root

- name: Copy powerlevel to root
  synchronize:
    dest: "/root/"
    src: "/home/{{ user.name }}/.p10k.zsh"
    archive: no

- name: zplug install as root
  shell: cmd="zplug install"
