---
- name: Clone dotfiles to user home
  become_user: "{{ user.name }}"
  become: yes
  git:
    repo: "{{ dotfiles.url }}"
    dest: /home/{{ user.name }}/{{ dotfiles.name }}
    recursive: yes
    bare: yes
    key_file: /home/{{ user.name }}/.ssh/id_rsa

- name: Checkout dotfiles
  become_user: "{{ user.name }}"
  become: yes
  command: git --git-dir=/home/{{ user.name }}/.dotfiles.git --work-tree=/home/{{ user.name }} checkout --force

- name: Remove README from home
  file:
    path: /home/{{ user.name }}/README.md
    state: absent

- name: Creates directory for runable scripts
  become_user: "{{ user.name }}"
  become: yes
  file:
    path: "/home/{{ user.name }}/.local/bin"
    state: directory
    mode: 0775
    recurse: yes

- include_tasks: zsh.yaml
#- include: bitwarden.yaml
