---
- name: Install bluetooth libraries and tools
  pacman:
    name:
      - bluez
      - bluez-libs
      - bluez-utils
      - bluez-tools
      - blueman
    state: present

- name: Make sure media-session dir exists
  file: path=/etc/pipewire/media-session.d/ state=directory mode="0755"

- name: Copy bluez-monitor.conf
  copy:
    src: bluez-monitor.conf
    dest: /etc/pipewire/media-session.d/bluez-monitor.conf

- name: Do not auto power on the bluetooth device
  command: gsettings set org.blueman.plugins.powermanager auto-power-on false
  become: yes
  become_user: "{{ user.name }}"

- name: Unblock the bluetooth service
  systemd: name="rfkill-block@bluetooth.service" enabled=no
  when: bluetooth.disable == False
  notify: Unblock bluetooth service

- name: Enable and start the bluetooth service
  systemd: name=bluetooth.service enabled=yes
  when: bluetooth.disable == False
  notify: start the bluetooth service

- name: Disable and stop the bluetooth service
  systemd: name=bluetooth.service enabled=no
  when: bluetooth.disable == True
  notify: stop the bluetooth service

- name: Block the bluetooth service
  systemd: name="rfkill-block@bluetooth.service" enabled=yes
  when: bluetooth.disable == True
  notify: Block bluetooth service
