---
- name: Start timesyncd
  systemd: name=systemd-timesyncd.service state=started
  when: ansible_virtualization_role == "host" or ansible_virtualization_role == "NA"

- name: Restart systemd-timesyncd
  service:
    name: systemd-timesyncd.service
    state: restarted
  when: ansible_virtualization_role == "host" or ansible_virtualization_role == "NA"
  listen: systemd-timesyncd configuration changed

- name: Write adjtime
  command: hwclock --systohc
  when: ansible_virtualization_role == "host" or ansible_virtualization_role == "NA"
  listen: systemd-timesyncd configuration changed
