---
- name: Copy touchpad configuration file
  ansible.builtin.copy: src=30-touchpad.conf dest=/etc/X11/xorg.conf.d/30-touchpad.conf
  tags:
    - libinput

- name: Copy logind configuration file
  ansible.builtin.copy: src=logind.conf dest=/etc/systemd/logind.conf

- name: Push low battery warning script
  ansible.builtin.copy: src=lowbatt.sh dest=/usr/local/bin/lowbatt mode=0755

- name: Push low battery warning service file
  ansible.builtin.template: src=lowbatt.service.j2 dest=/etc/systemd/system/lowbatt.service
  notify:
    - reload systemd config

- name: Push low battery timer file
  ansible.builtin.template: src=lowbatt.timer.j2 dest=/etc/systemd/system/lowbatt.timer
  notify:
    - reload systemd config
    - restart lowbatt

- name: Enable and start lowbatt timer
  systemd: name=lowbatt.timer enabled=yes
  notify: start lowbatt

- name: Install light
  pacman: name=light state=present

- name: Install powertop
  pacman: name=powertop state=present

#- name: Install powerstat
#  become: yes
#  become_user: "{{ user.name }}"
#  kewlfft.aur.aur: name=powerstat-git
#  tags:
#    - aur

- name: Install cmake for battery-stats
  pacman: name=cmake state=present

#- name: Install battery-stats
#  become: yes
#  become_user: "{{ user.name }}"
#  kewlfft.aur.aur: name=battery-stats-git
#  tags:
#    - aur

#- name: Install battop
#  become: yesblueproximity-py3-git
#  become_user: "{{ user.name }}"
#  aur:
#    name: battop
#    user: "{{ user.name }}"
#  tags:
#    - aur

- name: Install gestures
  when: desktop_environment == 'xfce-i3'
  block:
    - name: Install gestures prerequisites
      pacman:
        name:
          - wmctrl
          - xdotool
        state: present

    - name: Install gestures
      become: yes
      become_user: "{{ user.name }}"
      kewlfft.aur.aur: name=libinput-gestures
      tags:
        - aur

    - name: Add the user to the input groups
      user:
        name: "{{ user.name }}"
        groups: input
        append: yes
      tags:
        - user
