---
- name: Install filesystem packages
  ansible.builtin.package:
    name:
      - dosfstools
      - ntfs-3g
      - exfat-utils
    state: present

- name: Install btrfs tools
  block:
    - name: Install filesystem packages
      ansible.builtin.package:
        name:
          - btrfs-progs
          - snapper
        state: present

    - name: Check snapper config exists
      become: true
      ansible.builtin.stat:
        path: /etc/snapper/configs/root
      register: snapperconfig

    - name: Unmount .snapshots dir
      ansible.posix.mount:
        path: /.snapshots
        state: unmounted
      when: not snapperconfig.stat.exists

    - name: Remove .snapshots dir
      ansible.builtin.file:
        path: /.snapshots
        state: absent
      when: not snapperconfig.stat.exists

    - name: Create snapper config
      ansible.builtin.command: "snapper -c root create-config /"
      become: true
      when: not snapperconfig.stat.exists
  when: btrfs is defined and btrfs == True

- name: Include distribution specific btrfs tools
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - btrfs-{{ ansible_distribution }}.yaml
      skip: true
