---
- name: Enable gpg-agent.socket
  ansible.builtin.systemd:
    name: gpg-agent.socket
    scope: user
    enabled: yes
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  notify: start gpg-agent
  when: gnupg.enable_agent == True

- name: Enable dirmngr.socket
  ansible.builtin.systemd:
    name: dirmngr.socket
    scope: user
    enabled: yes
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  notify: start dirmngr
  when: gnupg.enable_agent == True

- name: Enable gpg-agent-ssh.socket
  ansible.builtin.systemd:
    name: gpg-agent-ssh.socket
    scope: user
    enabled: yes
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  notify: start gpg-agent-ssh
  when: gnupg.enable_agent == True and gnupg.emulate_ssh == True

- name: Create .gnupg dir
  ansible.builtin.file:
    path: /home/{{ user.name }}/.gnupg
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory
    mode: 0700
