---
- name: start user systemd instance
  ansible.builtin.systemd:
    name: "user@{{ user.uid }}"
    state: started
  when: running_in_chroot == False

- name: start gpg-agent
  systemd:
    name: gpg-agent.socket
    scope: user
    state: started
  when: running_in_chroot == False

- name: start dirmngr
  systemd:
    name: dirmngr.socket
    scope: user
    state: started
  when: running_in_chroot == False

- name: start gpg-agent-ssh
  systemd:
    name: gpg-agent-ssh.socket
    scope: user
    state: started
  when: running_in_chroot == False
