---
- name: Install TLP
  pacman:
    name:
      - x86_energy_perf_policy
      - ethtool
      - tlp
      - tlp-rdw
    state: present


- name: Push TLP battery threshold config
  ansible.builtin.copy:
    src: 20-battery.conf
    dest: /etc/tlp.d/
  notify:
    - restart tlp


- name: Push TLP radio device config
  ansible.builtin.copy:
    src: 20-rdw.conf
    dest: /etc/tlp.d/
  notify:
    - restart tlp


- name: Push TLP PCIe config
  ansible.builtin.copy:
    src: 20-pcie.conf
    dest: /etc/tlp.d/
  notify:
    - restart tlp


- name: Mask systemd radio service
  ansible.builtin.command: systemctl mask systemd-rfkill.service


- name: Mask systemd radio socket
  ansible.builtin.command: systemctl mask systemd-rfkill.socket


- name: Enable TLP
  systemd:
    name: tlp.service
    enabled: yes


- name: Install tlpui
  become: yes
  become_user: "{{ user.name }}"
  kewlfft.aur.aur: name=tlpui
  tags:
    - aur
