- name: Install nvidia video driver(s)
  pacman:
    name:
      - nvidia
      - nvidia-utils
      - nvidia-settings
      - lib32-nvidia-utils
    state: present

- name: Install nvidia dkms on hardened
  pacman:
    name: nvidia-dkms
    state: present
  when: hardened is defined
  tags:
    - hardened

- name: Install nvidia prime when more drivers are selected
  pacman:
    name: nvidia-prime
    state: present
  when: video_drivers|length > 1

- name: Copy nvidia kernel module config
  ansible.builtin.copy: src=nvidia.conf dest=/etc/modprobe.d/nvidia.conf

- name: Enable suspend/hibernate services for nvidia
  systemd:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - nvidia-hibernate
    - nvidia-suspend
