---
- name: Push ipv4 firewall config
  ansible.builtin.template: src=iptables.rules.j2 dest=/etc/iptables/iptables.rules

- name: Push ipv6 firewall config
  ansible.builtin.template: src=ip6tables.rules.j2 dest=/etc/iptables/ip6tables.rules
