---
- name: Install alsa-utils
  pacman:
    name: alsa-utils
    state: present

- name: Install PulseAudio
  pacman:
    name:
      - pipewire
      - pipewire-alsa
      - pipewire-pulse
      - wireplumber
      - pavucontrol
    state: present
