---
- name: Install gThumb
  pacman: name=gthumb state=present
  when: "'xfce' not in desktop_environment"

- name: Install ristretto
  pacman: name=ristretto state=present
  when: "'xfce' in desktop_environment"

- name: Install qrencode
  pacman: name=qrencode state=present

- name: Push qcode script
  ansible.builtin.copy: src=qcode.sh dest=/usr/local/bin/qcode mode=0755

- name: Install gtk theme
  pacman:
    name: arc-gtk-theme
    state: present

- name: Copy icon theme
  synchronize:
    dest: /usr/share/icons
    src: Green-Maia
  when: not ansible_check_mode

- name: Copy cursor theme
  synchronize:
    dest: /usr/share/icons
    src: Volantes-Cursors
  when: not ansible_check_mode

- name: Create background dir
  file: path=/usr/share/backgrounds state=directory

- name: Copy backround
  ansible.builtin.copy:
    dest: /usr/share/backgrounds/fight.jpg
    src: fight.jpg


