---
- name: install greenclip from AUR
  become: yes
  become_user: "{{ user.name }}"
  kewlfft.aur.aur:
    name: rofi-greenclip

- name: copy greenclip.service
  ansible.builtin.copy:
    src: greenclip.service
    dest: /etc/systemd/user/greenclip.service

- name: Enable greenclip.service
  systemd:
    name: greenclip.service
    scope: user
    enabled: yes
  notify: start greenclip service
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
